import json
import os
import logging
import re
from datetime import datetime

class CypressBuilder:
    def __init__(self, data_dir="data", e2e_dir="cypress/e2e/generated"):
        self.data_dir = data_dir
        self.e2e_dir = e2e_dir
        self.logger = logging.getLogger(__name__)

        if not os.path.exists(self.e2e_dir):
            os.makedirs(self.e2e_dir)
            
        # Initialize SelfHealer Memory Bank
        import importlib
        try:
            healer_mod = importlib.import_module("modules.09_self_healing.healer")
            self.healer = healer_mod.SelfHealer(data_dir=data_dir)
        except Exception as e:
            self.logger.warning(f"Self-Healer module unavailable. {e}")
            self.healer = None

    def _escape_selector(self, selector):
        """Escape special characters for safe Cypress selector usage inside backticks."""
        if not selector:
            return selector
        # Escape backticks that would break template literals
        escaped = selector.replace('`', '\\`')
        # Escape dollar signs that would trigger interpolation inside backticks
        escaped = escaped.replace('${', '\\${')
        return escaped

    def _escape_describe_text(self, text):
        """Escape text used in describe() and it() blocks."""
        if not text:
            return text
        return text.replace('`', "'").replace('${', '(').replace("'", "\\'")

    def _get_timeout_for_test(self, test_id, strategy):
        """Return context-appropriate timeout based on test type."""
        if "form" in test_id.lower() or "form" in strategy.lower():
            return 15000  # Forms may trigger server roundtrips
        elif "nav" in test_id.lower() or "routing" in strategy.lower():
            return 10000  # Navigation with routing
        elif "a11y" in test_id.lower():
            return 8000   # Accessibility scans need moderate time
        else:
            return 7000   # Simple interaction

    def write_spec(self, test_scenario, filepath, run_id):
        test_id = test_scenario["test_id"]
        raw_selector = test_scenario["selector_used"]
        selector = self._escape_selector(raw_selector)
        url = test_scenario.get("url", "/")
        scenario_desc = self._escape_describe_text(test_scenario["scenario"])
        strategy = test_scenario.get("strategy", "")
        timeout = self._get_timeout_for_test(test_id, strategy)
        
        # Self-Healing Injection: Query Memory Bank
        healed_selector = None
        if self.healer:
            healed_selector = self.healer.get_fallback(raw_selector)
            if healed_selector:
                healed_selector = self._escape_selector(healed_selector)

        content = f"""// AUTO-GENERATED BY QA AGENT
// Run ID: {run_id}
// Priority: {test_scenario.get('priority')} | Risk Level: {test_scenario.get('risk_level')}

describe('AUTO: {test_id} - {scenario_desc}', () => {{
  beforeEach(() => {{
    Cypress.config('defaultCommandTimeout', {timeout});
    cy.clearCookies();
    cy.clearLocalStorage();
    cy.visit('{url}');
    cy.on('uncaught:exception', (err, runnable) => {{
      return false;
    }});
  }});

  it('Executes the mapped selector action intelligently', () => {{
"""     
        # Update references for the remainder of the block to use robust mapping
        action_target = "robustSelector" if healed_selector else f"`{selector}`"
        
        # Inject Multi-Selector robustness if we learned a heal for it
        if healed_selector:
            content += f"    const robustSelector = `{selector}, {healed_selector}`;\n"

        # ===================================================================
        # TC_A11Y: Accessibility Testing (no element interaction needed)
        # ===================================================================
        if test_id.startswith("TC_A11Y"):
            content += """    // Accessibility Audit: Verify images have alt text and inputs have labels
    cy.get('img').each(($img) => {
      const alt = $img.attr('alt');
      const role = $img.attr('role');
      // Images should have alt text OR be decorative (role=presentation)
      if (role !== 'presentation' && role !== 'none') {
        expect(alt, `Image ${$img.attr('src') || 'unknown'} should have alt text`).to.exist;
        expect(alt.trim().length, 'Alt text should not be empty').to.be.greaterThan(0);
      }
    });

    // Verify form inputs have associated labels or aria-label
    cy.get('input:visible, select:visible, textarea:visible').each(($input) => {
      const id = $input.attr('id');
      const ariaLabel = $input.attr('aria-label');
      const ariaLabelledBy = $input.attr('aria-labelledby');
      const placeholder = $input.attr('placeholder');
      const type = $input.attr('type');
      
      // Skip hidden and submit/button types
      if (type === 'hidden' || type === 'submit' || type === 'button') return;
      
      const hasLabel = id ? Cypress.$$(`label[for="${id}"]`).length > 0 : false;
      const hasAccessibility = hasLabel || ariaLabel || ariaLabelledBy || placeholder;
      
      expect(hasAccessibility, `Input ${id || $input.attr('name') || 'unnamed'} should have a label or aria-label`).to.be.ok;
    });

    // Verify interactive elements are keyboard-focusable
    cy.get('button:visible, a:visible, [role="button"]:visible').each(($el) => {
      const tabIndex = $el.attr('tabindex');
      // Elements should not have tabindex="-1" (unfocusable) unless they have aria-hidden
      if (tabIndex === '-1' && !$el.attr('aria-hidden')) {
        cy.log(`Warning: ${$el.prop('tagName')} with text "${$el.text().substring(0, 30)}" is not keyboard-focusable`);
      }
    });
"""

        # ===================================================================
        # TC_SELECT: Dropdown Testing
        # ===================================================================
        elif test_id.startswith("TC_SELECT"):
            content += f"""    cy.get('body').then(($body) => {{
      if ($body.find({action_target}).length > 0) {{
        cy.get({action_target}).first().scrollIntoView();
        
        // Dropdown Testing: Select a non-default option and verify value change
        cy.get({action_target}).first().then(($select) => {{
          const options = $select.find('option');
          if (options.length > 1) {{
            // Pick the second option (first non-default)
            const targetValue = options.eq(1).val();
            const targetText = options.eq(1).text();
            cy.get({action_target}).first().select(targetValue, {{ force: true }});
            cy.get({action_target}).first().should('have.value', targetValue);
            cy.log(`Successfully selected "${{targetText}}" with value "${{targetValue}}"`);
          }} else {{
            cy.log('Dropdown has only one option, skipping selection test.');
          }}
        }});
      }} else {{
        cy.log('Dropdown element not found on this viewport, skipping.');
      }}
    }});
"""

        # ===================================================================
        # TC_TEXTAREA: Textarea Testing
        # ===================================================================
        elif test_id.startswith("TC_TEXTAREA"):
            content += f"""    cy.get('body').then(($body) => {{
      if ($body.find({action_target}).length > 0) {{
        cy.get({action_target}).first().scrollIntoView();
        
        // Textarea Testing: Type multi-line content and verify
        const testContent = 'Line 1 of test data.\\nLine 2 for multi-line validation.\\nSpecial chars: <>&"';
        cy.get({action_target}).first().clear({{ force: true }});
        cy.get({action_target}).first().type(testContent, {{ force: true }});
        cy.get({action_target}).first().should('not.have.value', '');
      }} else {{
        cy.log('Textarea element not found on this viewport, skipping.');
      }}
    }});
"""

        # ===================================================================
        # Standard test types (forms, nav, buttons)
        # ===================================================================
        else:
            content += f"    cy.get('body').then(($body) => {{\n"
            content += f"      if ($body.find({action_target}).length > 0) {{\n"
            content += f"        cy.get({action_target}).first().scrollIntoView();\n"
            
            if "Fill all inputs -> Submit" in strategy:
                content += f"""        // Positive E2E Form Fill
        cy.url().then((originalUrl) => {{
          cy.get({action_target}).within(() => {{
            cy.get('input:not([type="hidden"]):not([type="submit"])').each(($el) => {{
              if ($el.attr('type') === 'email') cy.wrap($el).clear({{force: true}}).type('test@example.com', {{force: true}});
              else if ($el.attr('type') === 'password') cy.wrap($el).clear({{force: true}}).type('Password123!', {{force: true}});
              else if ($el.attr('type') === 'number') cy.wrap($el).clear({{force: true}}).type('12345', {{force: true}});
              else if ($el.attr('type') === 'tel') cy.wrap($el).clear({{force: true}}).type('1234567890', {{force: true}});
              else cy.wrap($el).clear({{force: true}}).type('Test Data', {{force: true}});
            }});
            // Also fill textareas if present
            cy.get('textarea').each(($ta) => {{
              cy.wrap($ta).clear({{force: true}}).type('Test textarea content', {{force: true}});
            }});
            // Also select dropdowns if present
            cy.get('select').each(($sel) => {{
              const opts = $sel.find('option');
              if (opts.length > 1) {{
                cy.wrap($sel).select(opts.eq(1).val(), {{force: true}});
              }}
            }});
          }});
          cy.get({action_target}).first().submit();
          // Stronger assertion: verify page responded (URL changed OR success message OR readyState)
          cy.document().its('readyState').should('eq', 'complete');
          cy.get('body').then(($postBody) => {{
            const hasSuccess = $postBody.find('.success, .alert-success, .thank-you, [class*="success"]').length > 0;
            const urlChanged = cy.url().then((newUrl) => newUrl !== originalUrl);
            cy.log(hasSuccess ? '✅ Success indicator found after submission' : '⚠️ No explicit success indicator found');
          }});
        }});
"""
            elif "Leave inputs blank" in strategy:
                content += f"""        // Negative E2E Form Fill — submit empty and verify error handling
        cy.get({action_target}).first().submit();
        cy.document().its('readyState').should('eq', 'complete');
        // Check if validation messages appeared
        cy.get('body').then(($postBody) => {{
          const hasErrors = $postBody.find('.error, .alert-danger, .invalid-feedback, [class*="error"], :invalid').length > 0;
          cy.log(hasErrors ? '✅ Validation errors correctly displayed' : '⚠️ No validation feedback found after empty submit');
        }});
"""
            elif "Inject SQLi/NoSQL" in strategy:
                content += f"""        // Malformed E2E Form Fill — Security injection testing
        cy.get({action_target}).within(() => {{
          cy.get('input:not([type="hidden"]):not([type="submit"])').each(($el) => {{
             cy.wrap($el).clear({{force: true}}).type("' OR 1=1; --", {{force: true}});
          }});
        }});
        cy.get({action_target}).first().submit();
        // Verify the page didn't crash (500 error) — critical security check
        cy.document().its('readyState').should('eq', 'complete');
        cy.get('body').should('not.contain', 'Internal Server Error');
        cy.get('body').should('not.contain', 'syntax error');
        cy.get('body').should('not.contain', 'SQL');
"""
            elif test_id.startswith("TC_NAV") or "Click -> Wait for routing" in strategy:
                target_url = test_scenario.get("target_url", "")
                content += f"""        // E2E Navigation Trace — verify routing works
        cy.url().then((originalUrl) => {{
          cy.get({action_target}).first().click({{force: true}});
          cy.document().its('readyState').should('eq', 'complete');
          // Verify navigation actually occurred (URL changed or DOM updated)
          cy.url().then((newUrl) => {{
            if (newUrl !== originalUrl) {{
              cy.log(`✅ Navigation successful: ${{originalUrl}} → ${{newUrl}}`);
            }} else {{
              // URL didn't change — check if DOM content changed (SPA routing)
              cy.log('⚠️ URL unchanged — checking for SPA content update');
            }}
          }});
        }});
"""
            elif test_id.startswith("TC_BTN") or test_id.startswith("TC_INTERACT") or "Wait for DOM mutation" in strategy:
                content += f"""        // E2E Dynamic Interactivity — verify DOM mutation
        cy.get('body').then(($prebody) => {{
          const preCount = $prebody.find('*').length;
          cy.get({action_target}).first().click({{force: true}});
          cy.wait(800);
          cy.document().its('readyState').should('eq', 'complete');
          // Verify something changed in the DOM (modal, dropdown, accordion, etc.)
          cy.get('body').then(($postBody) => {{
            const postCount = $postBody.find('*').length;
            const diff = Math.abs(postCount - preCount);
            cy.log(`DOM mutation check: ${{preCount}} → ${{postCount}} elements (${{diff}} changed)`);
          }});
        }});
"""
            else:
                if "submit" in (selector or "") or "form" in (selector or ""):
                    content += f"        cy.get({action_target}).first().submit();\n"
                else:
                    content += f"        cy.get({action_target}).first().click({{force: true}});\n"
                content += "        cy.document().its('readyState').should('eq', 'complete');\n"
                
            content += f"""      }} else {{
        cy.log('Element not natively found on this viewport, skipping interactions.');
      }}
    }});
"""

        # Visual Regression Anchor at the end of every test
        content += f"""    // Visual Regression Anchor: Capture viewport snapshot
    cy.screenshot('{run_id}__{test_id}', {{ capture: 'viewport', overwrite: true }});
  }});
}});
"""

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        return True

    def build_test_suite(self, run_id):
        # 1. Clear out old generated tests
        for f in os.listdir(self.e2e_dir):
            if f.endswith(".cy.js"):
                os.remove(os.path.join(self.e2e_dir, f))

        prioritized_file = os.path.join(self.data_dir, f"{run_id}_prioritized.json")

        if not os.path.exists(prioritized_file):
            self.logger.error(f"Prioritized configuration file not found: {prioritized_file}")
            return False

        with open(prioritized_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        execution_plan = data.get("execution_plan", [])
        
        # 2. Iterate dynamically over the sorted plan
        generated_count: int = 0
        for i, scenario in enumerate(execution_plan):
            spec_name = f"{i+1:02d}_{scenario['test_id']}.cy.js"
            filepath = os.path.join(self.e2e_dir, spec_name)
            
            if self.write_spec(scenario, filepath, run_id):
                generated_count += 1

        self.logger.info(f"CypressBuilder generated {generated_count} executable `.cy.js` skeletons.")
        return True

if __name__ == "__main__":
    import sys
    logging.basicConfig(level=logging.INFO)
    builder = CypressBuilder()
    if len(sys.argv) > 1:
        builder.build_test_suite(sys.argv[1])
    else:
        builder.build_test_suite("run_20260301_160228")

